version: 2
updates:
  - package-ecosystem: "pip"
    directory: "app"
    schedule:
      interval: "monthly"
    # Disable version updates for hex dependencies
    open-pull-requests-limit: 0
      
  - package-ecosystem: "pip"
    directory: "core"
    schedule:
      interval: "monthly"
    # Disable version updates for hex dependencies
    open-pull-requests-limit: 0
