version: 2
updates:
  - package-ecosystem: "pip"
    directory: "app"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "pip"
    directory: "core"
    schedule:
      interval: "weekly"
